package autohandler

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	// skillName is the unique identifier and directory name for the skill.
	skillName = "understand-repo"
	// skillFile is the mandatory filename required by Copilot CLI.
	skillFile = "SKILL.md"
	// skillsDir is the directory under .github where Copilot CLI discovers project skills.
	skillsDir = "skills"
)

// UpdateCopilotSkill writes .github/skills/understand-repo/SKILL.md so that
// GitHub Copilot CLI can discover and invoke the skill via /skills list.
//
// The file is always overwritten to keep it in sync with the current
// repo-mapper output directory.
//
// repoRoot is the absolute path of the repository root.
// outputDir is the relative path of the repo-mapper output directory
// (e.g. ".repo-mapper"), as written to the generated README.
func UpdateCopilotSkill(repoRoot, outputDir string) error {
	skillDir := filepath.Join(repoRoot, defaultGithubDir, skillsDir, skillName)
	if err := os.MkdirAll(skillDir, 0o755); err != nil {
		return fmt.Errorf("create skill dir: %w", err)
	}

	targetPath := filepath.Join(skillDir, skillFile)
	content := buildSkillFile(outputDir)
	return writeFile(targetPath, content)
}

// buildSkillFile returns the full SKILL.md content for the understand-repo skill.
func buildSkillFile(outputDir string) string {
	// Use forward-slash paths so the Markdown is portable across OS.
	entrypoint := filepath.ToSlash(filepath.Join(outputDir, "README.md"))
	archFile := filepath.ToSlash(filepath.Join(outputDir, "architecture.md"))
	backendFile := filepath.ToSlash(filepath.Join(outputDir, "backend.md"))
	frontendFile := filepath.ToSlash(filepath.Join(outputDir, "frontend.md"))
	databaseFile := filepath.ToSlash(filepath.Join(outputDir, "database.md"))
	featuresFile := filepath.ToSlash(filepath.Join(outputDir, "features.md"))
	repoMapFile := filepath.ToSlash(filepath.Join(outputDir, "repo-map.json"))
	diagramsDir := filepath.ToSlash(filepath.Join(outputDir, "diagrams/"))

	var b strings.Builder

	// YAML frontmatter
	b.WriteString("---\n")
	fmt.Fprintf(&b, "name: %s\n", skillName)
	b.WriteString("description: >\n")
	b.WriteString("  Understand the structure, architecture, and components of this repository\n")
	b.WriteString("  by reading the repo-mapper documentation instead of crawling raw source files.\n")
	b.WriteString("  Use this skill whenever you need context about the codebase, how it is\n")
	b.WriteString("  organised, what technologies are used, or where specific functionality lives.\n")
	b.WriteString("---\n\n")

	// Markdown body
	fmt.Fprintf(&b, "# %s\n\n", skillName)
	b.WriteString("When you need to understand this repository — its architecture, module layout,\n")
	b.WriteString("technologies, APIs, database schema, or feature ownership — **read the\n")
	b.WriteString("repo-mapper documentation first**. It is a structured, always-up-to-date map\n")
	b.WriteString("of the entire codebase generated by\n")
	b.WriteString("[repo-mapper](https://github.com/anushibinj/repo-mapper).\n\n")

	b.WriteString("## Step 1 — Read the entrypoint\n\n")
	fmt.Fprintf(&b, "Open `%s`. It contains:\n\n", entrypoint)
	b.WriteString("- **Snapshot** — current branch and commit\n")
	b.WriteString("- **Languages** — every language and its file count\n")
	b.WriteString("- **Modules** — detected sub-modules (frontend, backend, etc.)\n")
	b.WriteString("- **Contents** — links to all detailed views\n\n")
	b.WriteString("Read this file **before** opening any source file.\n\n")

	b.WriteString("## Step 2 — Follow the links for the area you care about\n\n")
	b.WriteString("| You want to know about… | Read this file |\n")
	b.WriteString("|---|---|\n")
	fmt.Fprintf(&b, "| High-level system layers / diagrams | `%s` |\n", archFile)
	fmt.Fprintf(&b, "| Controllers, services, repositories, APIs | `%s` |\n", backendFile)
	fmt.Fprintf(&b, "| Pages, components, hooks, routes | `%s` |\n", frontendFile)
	fmt.Fprintf(&b, "| Tables, columns, foreign keys | `%s` |\n", databaseFile)
	fmt.Fprintf(&b, "| Cross-cutting feature ownership | `%s` |\n", featuresFile)
	fmt.Fprintf(&b, "| Full machine-readable model | `%s` |\n", repoMapFile)
	fmt.Fprintf(&b, "| System / ER diagrams (Mermaid) | `%s` |\n\n", diagramsDir)

	b.WriteString("## Step 3 — Open source files only for implementation details\n\n")
	b.WriteString("Once you know *where* something lives from the map, open only the specific\n")
	b.WriteString("source file you need. Do not crawl the repository tree looking for context —\n")
	b.WriteString("the map already provides it.\n\n")

	b.WriteString("## When the map does not exist\n\n")
	fmt.Fprintf(&b, "If `%s` is missing, the repository has not been scanned\n", entrypoint)
	b.WriteString("yet. Ask the user to run:\n\n")
	b.WriteString("```bash\n")
	b.WriteString("repo-mapper scan\n")
	b.WriteString("```\n\n")
	b.WriteString("This will generate the full documentation set in `" + outputDir + "`.\n")

	return b.String()
}
