flowchart TD
    AuthController[AuthController]
    BillingController[BillingController]
    AuthService(AuthService)
    BillingService(BillingService)
    BillingRepository[(BillingRepository)]
    AuthController --> AuthService
    BillingController --> BillingService
    BillingService --> BillingRepository
