package generator

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/anushibinj/repo-mapper/internal/model"
)

// WriteMarkdown renders README.md, backend.md, frontend.md, architecture.md,
// database.md, and features.md (PRD section 13, "Markdown").
func WriteMarkdown(repo *model.Repository, outputDir string) error {
	files := map[string]string{
		"README.md":       renderReadme(repo),
		"backend.md":      renderBackend(repo),
		"frontend.md":     renderFrontend(repo),
		"architecture.md": renderArchitecture(repo),
		"database.md":     renderDatabase(repo),
		"features.md":     renderFeatures(repo),
	}
	for name, content := range files {
		if err := writeFile(filepath.Join(outputDir, name), content); err != nil {
			return err
		}
	}
	return nil
}

func renderReadme(repo *model.Repository) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s — Repository Map\n\n", nonEmpty(repo.Name, "Repository"))
	b.WriteString("This directory is generated by [Repo Mapper](https://github.com/anushibinj/repo-mapper). ")
	b.WriteString("It is the first source of truth for AI assistants and developers exploring this repository — ")
	b.WriteString("read this before opening source files.\n\n")

	if repo.Git.CommitHash != "" || repo.Git.Branch != "" {
		b.WriteString("## Snapshot\n\n")
		if repo.Git.Branch != "" {
			fmt.Fprintf(&b, "- Branch: `%s`\n", repo.Git.Branch)
		}
		if repo.Git.CommitHash != "" {
			fmt.Fprintf(&b, "- Commit: `%s`\n", repo.Git.CommitHash)
		}
		b.WriteString("\n")
	}

	b.WriteString("## Languages\n\n")
	if len(repo.Languages) == 0 {
		b.WriteString("_No languages detected._\n\n")
	} else {
		b.WriteString("| Language | Files |\n|---|---|\n")
		for _, l := range repo.Languages {
			fmt.Fprintf(&b, "| %s | %d |\n", l.Name, l.FileCount)
		}
		b.WriteString("\n")
	}

	b.WriteString("## Modules\n\n")
	if len(repo.Modules) == 0 {
		b.WriteString("_No modules detected._\n\n")
	} else {
		b.WriteString("| Module | Path | Kind |\n|---|---|---|\n")
		for _, m := range repo.Modules {
			fmt.Fprintf(&b, "| %s | %s | %s |\n", m.Name, m.Path, m.Kind)
		}
		b.WriteString("\n")
	}

	fmt.Fprintf(&b, "## Contents\n\n")
	b.WriteString("- [architecture.md](architecture.md) — high-level system architecture\n")
	b.WriteString("- [backend.md](backend.md) — controllers, services, repositories, APIs\n")
	b.WriteString("- [frontend.md](frontend.md) — pages, components, hooks, routes\n")
	b.WriteString("- [database.md](database.md) — tables and relationships\n")
	b.WriteString("- [features.md](features.md) — cross-cutting feature ownership\n")
	b.WriteString("- [diagrams/](diagrams/) — Mermaid diagrams\n")
	b.WriteString("- [repo-map.json](repo-map.json) — full canonical model\n")

	return b.String()
}

func renderBackend(repo *model.Repository) string {
	var b strings.Builder
	b.WriteString("# Backend\n\n")

	kinds := []string{"controller", "service", "repository", "entity", "bean"}
	for _, kind := range kinds {
		comps := filterComponents(repo.Components, kind)
		if len(comps) == 0 {
			continue
		}
		fmt.Fprintf(&b, "## %s\n\n", pluralize(kind))
		b.WriteString("| Name | File | Depends On |\n|---|---|---|\n")
		for _, c := range comps {
			fmt.Fprintf(&b, "| %s | %s | %s |\n", c.Name, c.File, strings.Join(c.DependsOn, ", "))
		}
		b.WriteString("\n")
	}

	if len(repo.APIs) > 0 {
		b.WriteString("## API Endpoints\n\n")
		b.WriteString("| Method | Path | Controller | Handler |\n|---|---|---|---|\n")
		for _, a := range repo.APIs {
			fmt.Fprintf(&b, "| %s | %s | %s | %s |\n", a.Method, a.Path, a.Controller, a.Handler)
		}
		b.WriteString("\n")
	}

	if len(repo.APIs) == 0 && allEmpty(repo.Components, kinds) {
		b.WriteString("_No backend components detected._\n")
	}

	return b.String()
}

func renderFrontend(repo *model.Repository) string {
	var b strings.Builder
	b.WriteString("# Frontend\n\n")

	kinds := []string{"page", "container", "component", "hook"}
	for _, kind := range kinds {
		comps := filterComponents(repo.Components, kind)
		if len(comps) == 0 {
			continue
		}
		fmt.Fprintf(&b, "## %s\n\n", pluralize(kind))
		b.WriteString("| Name | File | API Calls |\n|---|---|---|\n")
		for _, c := range comps {
			fmt.Fprintf(&b, "| %s | %s | %s |\n", c.Name, c.File, strings.Join(c.Calls, ", "))
		}
		b.WriteString("\n")
	}

	if len(repo.Routes) > 0 {
		b.WriteString("## Routes\n\n")
		b.WriteString("| Path | Component | File |\n|---|---|---|\n")
		for _, r := range repo.Routes {
			fmt.Fprintf(&b, "| %s | %s | %s |\n", r.Path, r.Component, r.File)
		}
		b.WriteString("\n")
	}

	if len(repo.Routes) == 0 && allEmpty(repo.Components, kinds) {
		b.WriteString("_No frontend components detected._\n")
	}

	return b.String()
}

func renderArchitecture(repo *model.Repository) string {
	var b strings.Builder
	b.WriteString("# Architecture\n\n")
	b.WriteString("See [diagrams/system.mmd](diagrams/system.mmd) for the high-level system diagram, ")
	b.WriteString("[diagrams/backend.mmd](diagrams/backend.mmd) and [diagrams/frontend.mmd](diagrams/frontend.mmd) ")
	b.WriteString("for layered views, and [diagrams/database.mmd](diagrams/database.mmd) for the data model.\n\n")

	hasFrontend := hasAnyComponent(repo.Components, "page", "container", "component", "hook")
	hasBackend := hasAnyComponent(repo.Components, "controller", "service", "repository")
	hasDB := len(repo.Tables) > 0

	b.WriteString("## Layers Detected\n\n")
	fmt.Fprintf(&b, "- Frontend: %s\n", yesNo(hasFrontend))
	fmt.Fprintf(&b, "- Backend: %s\n", yesNo(hasBackend))
	fmt.Fprintf(&b, "- Database: %s\n", yesNo(hasDB))
	b.WriteString("\n")

	if len(repo.Features) > 0 {
		b.WriteString("## Features\n\n")
		for _, f := range repo.Features {
			fmt.Fprintf(&b, "- **%s** — see [features.md](features.md)\n", f.Name)
		}
	}

	return b.String()
}

func renderDatabase(repo *model.Repository) string {
	var b strings.Builder
	b.WriteString("# Database\n\n")
	if len(repo.Tables) == 0 {
		b.WriteString("_No tables detected._\n")
		return b.String()
	}

	for _, t := range repo.Tables {
		fmt.Fprintf(&b, "## %s\n\n", t.Name)
		if t.Entity != "" {
			fmt.Fprintf(&b, "Mapped entity: `%s`\n\n", t.Entity)
		}
		if len(t.Columns) > 0 {
			b.WriteString("| Column | Type | PK | FK |\n|---|---|---|---|\n")
			for _, c := range t.Columns {
				pk := ""
				if c.PrimaryKey {
					pk = "✓"
				}
				fmt.Fprintf(&b, "| %s | %s | %s | %s |\n", c.Name, c.Type, pk, c.ForeignKey)
			}
			b.WriteString("\n")
		}
		if len(t.RelatesTo) > 0 {
			fmt.Fprintf(&b, "Relates to: %s\n\n", strings.Join(t.RelatesTo, ", "))
		}
	}

	return b.String()
}

func renderFeatures(repo *model.Repository) string {
	var b strings.Builder
	b.WriteString("# Features\n\n")
	if len(repo.Features) == 0 {
		b.WriteString("_No cross-cutting features detected yet. Features are inferred from naming ")
		b.WriteString("conventions shared across frontend/backend/database layers._\n")
		return b.String()
	}

	for _, f := range repo.Features {
		fmt.Fprintf(&b, "## %s\n\n", f.Name)
		if len(f.Frontend) > 0 {
			fmt.Fprintf(&b, "- Frontend: %s\n", strings.Join(f.Frontend, ", "))
		}
		if len(f.Backend) > 0 {
			fmt.Fprintf(&b, "- Backend: %s\n", strings.Join(f.Backend, ", "))
		}
		if len(f.APIs) > 0 {
			fmt.Fprintf(&b, "- APIs: %s\n", strings.Join(f.APIs, ", "))
		}
		if len(f.Database) > 0 {
			fmt.Fprintf(&b, "- Database: %s\n", strings.Join(f.Database, ", "))
		}
		b.WriteString("\n")
	}

	return b.String()
}

func filterComponents(components []model.Component, kind string) []model.Component {
	var out []model.Component
	for _, c := range components {
		if c.Kind == kind {
			out = append(out, c)
		}
	}
	return out
}

func hasAnyComponent(components []model.Component, kinds ...string) bool {
	set := map[string]bool{}
	for _, k := range kinds {
		set[k] = true
	}
	for _, c := range components {
		if set[c.Kind] {
			return true
		}
	}
	return false
}

func allEmpty(components []model.Component, kinds []string) bool {
	return !hasAnyComponent(components, kinds...)
}

func yesNo(b bool) string {
	if b {
		return "yes"
	}
	return "no"
}

func nonEmpty(s, fallback string) string {
	if s == "" {
		return fallback
	}
	return s
}

func titleCase(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// pluralize renders a component-kind label as a section heading, handling
// the small set of irregular plurals ("repository" -> "Repositories",
// "entity" -> "Entities") that a naive "+s" would mangle.
func pluralize(kind string) string {
	if strings.HasSuffix(kind, "y") && len(kind) > 1 {
		prev := kind[len(kind)-2]
		if prev != 'a' && prev != 'e' && prev != 'i' && prev != 'o' && prev != 'u' {
			return titleCase(kind[:len(kind)-1] + "ies")
		}
	}
	return titleCase(kind) + "s"
}
